/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package json.parsor;

import json.parsor.builder.ObjectBuilder;
import json.parsor.tokeniser.Token;
import json.parsor.tokeniser.Tokeniser;

import java.lang.reflect.InvocationTargetException;

public class PSON<MapperClass> {

    private String jsonString;


    public PSON(String jsonString){
        this.jsonString = jsonString;

    }
    public String stringify(Object obj){
        return "";
    }

    @SuppressWarnings("unchecked")
    public Object parseIntoObject(MapperClass mapperObject) throws InvocationTargetException, NoSuchMethodException, IllegalAccessException, InstantiationException {
        Tokeniser tokeniser = new Tokeniser(this.jsonString);
        ObjectBuilder builder = new ObjectBuilder(tokeniser.getTokens(),mapperObject);

        mapperObject = (MapperClass) builder.build();

        return mapperObject;
    }
}
