/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package json.parsor;

import json.parsor.tokeniser.Token;
import json.parsor.tokeniser.Tokeniser;

public class PSON<MapperClass> {

    private String jsonString;

    public void PSON(String jsonString){
        this.jsonString = jsonString;

    }
    public String stringify(Object obj){
        return "";
    }

    public MapperClass parse(String s){
        MapperClass m  = null;

        return m;
    }
}
