/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package json.parsor;

import json.parsor.builder.ObjectBuilder;
import json.parsor.tokeniser.Token;
import json.parsor.tokeniser.Tokeniser;

import java.lang.reflect.InvocationTargetException;

public class PSON<MapperClass> {

    @SuppressWarnings("unchecked")
    public Object parseIntoObject(String jsonString, MapperClass mapperObject) throws InvocationTargetException, NoSuchMethodException, IllegalAccessException, InstantiationException {
        Tokeniser tokeniser = new Tokeniser(jsonString);
        ObjectBuilder builder = new ObjectBuilder(tokeniser.getTokens(),mapperObject);

        mapperObject = (MapperClass) builder.build();

        return mapperObject;
    }

    public String stringify(MapperClass mapperObject){
        return "";
    }
}
