/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package json.parsor;

import json.parsor.tokeniser.Token;
import json.parsor.tokeniser.Tokeniser;
import org.junit.Test;

import java.lang.reflect.Field;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void someLibraryMethodReturnsTrue() {
        PSON pson = new PSON<MapperClass>();
        String jsonString = "{\"name\":\"Aman\",\"age\":24,\"isEducated\":false,\"hobbies\":[\"cricket\",\"badminton\",\"guitar\",\"movies\"],\"class10\":{\"isPassed\":true,\"year\":2016,\"board\":\"CBSE\"},\"class12\":{\"isPassed\":true,\"year\":2018,\"board\":\"CBSE\"},\"UG\":{\"isPassed\":true,\"year\":2023,\"board\":\"NITJSR\"}}";
        Tokeniser tokeniser = new Tokeniser(jsonString);
        for(Token token: tokeniser.getTokens()){
            System.out.println(token.getTokenType());
            System.out.println(token.getTokenValue());
            System.out.println("----------------------------------------------------");
        }
    }
}
