/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package json;

import json.builder.object.ObjectBuilder;
import json.parsor.Tokeniser;

import java.lang.reflect.InvocationTargetException;

public class PSON<MapperClass> {

    @SuppressWarnings("unchecked")
    public Object parseIntoObject(String jsonString, MapperClass mapperObject) throws InvocationTargetException, NoSuchMethodException, IllegalAccessException, InstantiationException {
        Tokeniser tokeniser = new Tokeniser(jsonString);
        ObjectBuilder builder = new ObjectBuilder(tokeniser.getTokens(),mapperObject);

        mapperObject = (MapperClass) builder.build();

        return mapperObject;
    }

    public String stringify(MapperClass mapperObject){
        return "";
    }
}
